name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: potictac
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '9.0.100-preview.2.24157.14'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        include-prerelease: true

    - name: Build React Client
      run: |
        npm install
        npm run build
        mkdir -p server/server/PoTicTacServer/wwwroot
        cp -r build/* server/server/PoTicTacServer/wwwroot/

    - name: Build and publish API
      run: |
        cd server/server/PoTicTacServer
        dotnet restore --configfile ../../../NuGet.config
        dotnet build --configuration Release
        dotnet publish -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: server/server/PoTicTacServer/publish